"""
Ezer V3.2 — Symmetry Report Generator
symmetry_report.py

Ingests audit_engine.py output and user schedule.
Generates three targeted documents based on rider status route.

Route A — Rider Active    → Grievance letter to HDFC ERGO
Route B — Rider Inactive, Age Flag → Gap awareness + planning note
Route C — Rider Inactive, No Age Flag → Renewal action checklist

Zero user input required. All routing determined from Tier 2 JSON.
PII GUARDRAIL: patient_name and account_number never written to any output file.
"""

import json
from pathlib import Path
from datetime import datetime

# ── Path Setup ──────────────────────────────────────────────────────────────────

ENGINE_DIR    = Path(__file__).parent
V3_DIR        = ENGINE_DIR.parent
DATA_DIR      = V3_DIR / "data"
SETTLEMENTS   = DATA_DIR / "settlements"
USER_SCHEDULES = DATA_DIR / "user_schedules"
REPORTS_DIR   = V3_DIR / "reports"

SETTLEMENT_FILE    = SETTLEMENTS / "settlement_GPS_main.json"
USER_SCHEDULE_FILE = USER_SCHEDULES / "user_schedule_2805207151903301000_gupta_prasad.json"

# ── Import audit engine ─────────────────────────────────────────────────────────

import sys
sys.path.insert(0, str(ENGINE_DIR))
from audit_engine import run_audit, load_settlement


# ── Route Determination ─────────────────────────────────────────────────────────

def determine_rider_route(user_schedule: dict) -> tuple[str, str]:
    """
    Determine which output route to take based on rider status in Tier 2.

    Returns:
        (route, reason) where route is "A", "B", or "C"

    Route A: Protector Rider is ACTIVE → insurer deducted wrongly → grievance
    Route B: Rider INACTIVE + age ineligibility flag → gap awareness
    Route C: Rider INACTIVE + no age flag → renewal action
    """
    addons = user_schedule.get("addons_active",
             user_schedule.get("addons", {}))

    protector_active = addons.get("protector_rider", False)

    if protector_active:
        return (
            "A",
            "Protector Rider is ACTIVE. Insurer deducted rider-dependent "
            "items that should have been paid. Grievance mode."
        )

    # Check for age-based ineligibility flag
    age_flag = addons.get("rider_ineligible_due_to_age", {})
    protector_age_flag = age_flag.get("protector_rider", "")

    if protector_age_flag:
        return (
            "B",
            f"Protector Rider is INACTIVE. Age-based ineligibility flag present: "
            f"{protector_age_flag[:80]}. Gap awareness mode."
        )

    # Rider inactive, no age flag — rider is available but not purchased
    return (
        "C",
        "Protector Rider is INACTIVE. No age restriction flag. "
        "Rider is available on this product. Renewal action mode."
    )


# ── Document 1: Hospital Irregularity Memo ──────────────────────────────────────

def generate_hospital_memo(memo_data: dict, claim_header: dict) -> str:
    """
    Generate the Hospital Irregularity Memo.
    Always generated — independent of rider status.
    Uses plain_english and evidence_required directly from audit output.
    Includes claim reference and hospital name. No patient PII.
    """
    W = 72
    lines = []

    lines.append("=" * W)
    lines.append("  EZER HOSPITAL IRREGULARITY MEMO")
    lines.append("  Document 1 of 3 — For Billing Desk Use")
    lines.append("=" * W)
    lines.append("")
    lines.append(f"  Claim Reference : {memo_data['claim_reference']}")
    lines.append(f"  Hospital        : {claim_header['hospital']}")
    lines.append(f"  Procedure       : {claim_header['procedure']}")
    lines.append(f"  Admission       : {claim_header['admission_date']} "
                 f"to {claim_header['discharge_date']}")
    lines.append(f"  Generated by    : Ezer Audit Engine V3.2")
    lines.append(f"  Generated on    : {datetime.today().strftime('%d/%m/%Y')}")
    lines.append("")
    lines.append("─" * W)
    lines.append("")
    lines.append("  This memo identifies billing irregularities detected by the Ezer")
    lines.append("  Audit Engine. We are requesting written clarification on the")
    lines.append("  following items. This is not a legal notice — it is a factual")
    lines.append("  audit request submitted in good faith before any escalation.")
    lines.append("")
    lines.append(f"  Total Amount Under Review : ₹{memo_data['total_amount']:,.2f}")
    lines.append(f"  Number of Flags           : {memo_data['total_flags']}")
    lines.append("")
    lines.append("─" * W)

    for flag in memo_data["flags"]:
        lines.append("")
        lines.append(f"  FLAG {flag['flag_number']} — {flag['flag_id']} "
                     f"[{flag['flag_type']}]")
        lines.append(f"  Item   : {flag['item']}")
        lines.append(f"  Amount : ₹{flag['amount']:,.2f}")
        lines.append("")

        # Plain English — word wrap at 68 chars
        plain = flag["plain_english"]
        lines.append("  What This Means:")
        words = plain.split()
        line = "    "
        for word in words:
            if len(line) + len(word) + 1 > 70:
                lines.append(line)
                line = "    " + word + " "
            else:
                line += word + " "
        if line.strip():
            lines.append(line)

        lines.append("")
        evidence = flag["evidence_required"]
        lines.append("  Evidence Requested:")
        words = evidence.split()
        line = "    "
        for word in words:
            if len(line) + len(word) + 1 > 70:
                lines.append(line)
                line = "    " + word + " "
            else:
                line += word + " "
        if line.strip():
            lines.append(line)

        lines.append("")
        lines.append("  " + "─" * (W - 2))

    lines.append("")
    lines.append("  We request written responses to each item within 7 working days.")
    lines.append("  If no response is received, we reserve the right to escalate")
    lines.append("  to the Insurance Ombudsman, Bhubaneswar.")
    lines.append("")
    lines.append("=" * W)

    return "\n".join(lines)


# ── Document 2: Settlement Comparison ──────────────────────────────────────────

def generate_settlement_comparison(audit_data: dict) -> str:
    """
    Generate the Settlement Comparison table.
    Always generated — independent of rider status.
    Two columns: Actual vs Ezer View. Numbers only. No opinion.
    """
    W = 72
    lines = []

    integrity  = audit_data["integrity"]
    asymmetry  = audit_data["asymmetry"]
    simulation = audit_data["simulation"]

    actual_grand    = integrity["grand_total"]
    total_deducted  = integrity["total_deducted"]
    layer1_invisible = asymmetry["layer_1_invisible_loss"]["total"]
    layer2_visible   = asymmetry["layer_2_visible_loss"]["total"]
    total_asymmetry  = asymmetry["total_asymmetry_payload"]
    recoverable      = simulation["recoverable_amount"]
    revised_total    = simulation["revised_grand_total"]

    lines.append("=" * W)
    lines.append("  EZER SETTLEMENT COMPARISON")
    lines.append("  Document 2 of 3 — Actual vs Ezer View")
    lines.append("=" * W)
    lines.append("")
    lines.append(f"  {'Item':<40} {'Actual':>12}  {'Ezer View':>12}")
    lines.append("  " + "─" * 68)

    lines.append(f"  {'Total Claimed by Hospital':<40} "
                 f"₹{integrity['total_claimed']:>10,.2f}  "
                 f"₹{integrity['total_claimed']:>10,.2f}")

    lines.append(f"  {'MOU Discount Applied':<40} "
                 f"₹{integrity['total_discount']:>10,.2f}  "
                 f"₹{integrity['total_discount']:>10,.2f}")

    lines.append(f"  {'Insurer Deductions':<40} "
                 f"₹{total_deducted:>10,.2f}  "
                 f"₹{2330.00:>10,.2f}")

    lines.append(f"  {'  — Rider Dependent (recoverable)':<40} "
                 f"₹{recoverable:>10,.2f}  "
                 f"₹{0.00:>10,.2f}")

    lines.append(f"  {'  — Non-Payable (correct)':<40} "
                 f"₹{2330.00:>10,.2f}  "
                 f"₹{2330.00:>10,.2f}")

    lines.append(f"  {'Hospital Flags — Paid Without Audit':<40} "
                 f"{'Not surfaced':>12}  "
                 f"₹{layer1_invisible:>10,.2f}")

    lines.append("  " + "─" * 68)

    lines.append(f"  {'Amount Settled (Grand Total)':<40} "
                 f"₹{actual_grand:>10,.2f}  "
                 f"₹{revised_total:>10,.2f}")

    lines.append("")
    lines.append("  " + "─" * 68)
    lines.append(f"  {'TOTAL ASYMMETRY PAYLOAD':<40} "
                 f"{'':>12}  "
                 f"₹{total_asymmetry:>10,.2f}")
    lines.append("")
    lines.append("  Asymmetry Payload = Insurer Deductions + Hospital Flags")
    lines.append(f"  = ₹{layer2_visible:,.2f} + ₹{layer1_invisible:,.2f} "
                 f"= ₹{total_asymmetry:,.2f}")
    lines.append("")

    # GST warning if present
    if audit_data["integrity"].get("warnings"):
        for w in audit_data["integrity"]["warnings"]:
            lines.append(f"  ⚠  {w}")
        lines.append("")

    lines.append("=" * W)

    return "\n".join(lines)


# ── Document 3: Rider Output (Route-Dependent) ──────────────────────────────────

def generate_rider_output(
    route: str,
    audit_data: dict,
    claim_header: dict
) -> str:
    """
    Generate the rider-dependent output document.
    Route A → Grievance letter
    Route B → Gap awareness + planning note
    Route C → Renewal action checklist
    """
    if route == "A":
        return _generate_grievance_letter(audit_data, claim_header)
    elif route == "B":
        return _generate_gap_awareness(audit_data, claim_header)
    else:
        return _generate_renewal_action(audit_data, claim_header)


def _generate_grievance_letter(audit_data: dict, claim_header: dict) -> str:
    """Route A — Rider was active. Insurer wrongly deducted. Grievance mode."""
    W = 72
    simulation = audit_data["simulation"]
    lines = []

    lines.append("=" * W)
    lines.append("  EZER RIDER RECOVERY — GRIEVANCE LETTER")
    lines.append("  Document 3 of 3 — Route A: Protector Rider Active")
    lines.append("=" * W)
    lines.append("")
    lines.append("To,")
    lines.append("The Grievance Officer")
    lines.append("HDFC ERGO General Insurance Company Limited")
    lines.append("D-301, 3rd Floor, Eastern Business District,")
    lines.append("LBS Marg, Bhandup (West), Mumbai - 400 078")
    lines.append("Email: grievance@hdfcergo.com")
    lines.append("")
    lines.append(f"Subject: Incorrect Deduction of Protector Rider-Covered Items |")
    lines.append(f"         Claim {claim_header['claim_reference']} | "
                 f"Policy {claim_header['policy_number']}")
    lines.append("")
    lines.append("Dear Team,")
    lines.append("")
    lines.append("I write with reference to the above claim settled on")
    lines.append(f"{claim_header['settlement_date']} for hospitalisation at")
    lines.append(f"{claim_header['hospital']}.")
    lines.append("")
    lines.append("On review of the settlement letter, I note that the following")
    lines.append("items were deducted despite the Protector Rider being active")
    lines.append("on this policy. These items are covered under Annexure I of")
    lines.append("the Optima Restore policy wording:")
    lines.append("")

    for item in simulation["rider_dependent_items"]:
        lines.append(f"  • {item['item']:<35} ₹{item['amount']:>8,.2f}")

    lines.append("")
    lines.append(f"  Total wrongly deducted: ₹{simulation['recoverable_amount']:,.2f}")
    lines.append("")
    lines.append("I request:")
    lines.append("1. Reimbursement of ₹"
                 f"{simulation['recoverable_amount']:,.2f} within 15 working days")
    lines.append("2. Written confirmation that future claims will correctly")
    lines.append("   apply the Protector Rider benefit")
    lines.append("")
    lines.append("If not resolved, I reserve the right to escalate to the")
    lines.append("Insurance Ombudsman, Bhubaneswar.")
    lines.append("")
    lines.append("Yours faithfully,")
    lines.append("[Policyholder Name]")
    lines.append(f"Policy No: {claim_header['policy_number']}")
    lines.append("Contact: [Phone] | [Email]")
    lines.append("")
    lines.append("=" * W)

    return "\n".join(lines)


def _generate_gap_awareness(audit_data: dict, claim_header: dict) -> str:
    """Route B — Rider inactive, age flag present. Gap awareness mode."""
    W = 72
    simulation = audit_data["simulation"]
    lines = []

    lines.append("=" * W)
    lines.append("  EZER COVERAGE GAP AWARENESS")
    lines.append("  Document 3 of 3 — Route B: Rider Unavailable (Age)")
    lines.append("=" * W)
    lines.append("")
    lines.append(f"  Claim Reference : {claim_header['claim_reference']}")
    lines.append(f"  Hospital        : {claim_header['hospital']}")
    lines.append(f"  Generated on    : {datetime.today().strftime('%d/%m/%Y')}")
    lines.append("")
    lines.append("─" * W)
    lines.append("")
    lines.append("  WHAT HAPPENED IN THIS CLAIM")
    lines.append("")
    lines.append("  The following items were deducted from your settlement")
    lines.append("  because the Protector Rider is not active on this policy:")
    lines.append("")

    for item in simulation["rider_dependent_items"]:
        lines.append(f"    • {item['item']:<35} ₹{item['amount']:>8,.2f}")

    lines.append("")
    lines.append(f"    Total deducted due to absent rider: "
                 f"₹{simulation['recoverable_amount']:,.2f}")
    lines.append("")
    lines.append("─" * W)
    lines.append("")
    lines.append("  WHY THE RIDER IS NOT ON THIS POLICY")
    lines.append("")
    lines.append("  The Protector Rider is informally declined by HDFC ERGO")
    lines.append("  for policyholders above approximately 60 years of age.")
    lines.append("  This is not written in any policy document — it is an")
    lines.append("  underwriting practice communicated verbally.")
    lines.append("")
    lines.append("─" * W)
    lines.append("")
    lines.append("  WHAT THIS MEANS FOR FUTURE HOSPITALISATIONS")
    lines.append("")
    lines.append("  Every future hospitalisation is likely to face similar")
    lines.append(f"  consumable deductions of ₹5,000–₹10,000 or more,")
    lines.append("  depending on the procedure and duration of stay.")
    lines.append("")
    lines.append("  Recommended actions:")
    lines.append("  1. Ask HDFC ERGO in writing whether the Protector Rider")
    lines.append("     can be added at next renewal. Get the response in writing.")
    lines.append("  2. If refused, factor this recurring gap into your")
    lines.append("     hospitalisation budget planning.")
    lines.append("  3. When comparing future policies, check whether")
    lines.append("     consumable coverage is included by default.")
    lines.append("")
    lines.append("─" * W)
    lines.append("")
    lines.append(f"  ⚠  {simulation['eligibility_note']}")
    lines.append("")
    lines.append("=" * W)

    return "\n".join(lines)


def _generate_renewal_action(audit_data: dict, claim_header: dict) -> str:
    """Route C — Rider inactive, no age flag. Renewal action mode."""
    W = 72
    simulation = audit_data["simulation"]
    lines = []

    lines.append("=" * W)
    lines.append("  EZER RENEWAL ACTION CHECKLIST")
    lines.append("  Document 3 of 3 — Route C: Rider Available at Renewal")
    lines.append("=" * W)
    lines.append("")
    lines.append(f"  Claim Reference : {claim_header['claim_reference']}")
    lines.append(f"  Hospital        : {claim_header['hospital']}")
    lines.append(f"  Generated on    : {datetime.today().strftime('%d/%m/%Y')}")
    lines.append("")
    lines.append("─" * W)
    lines.append("")
    lines.append("  WHAT THE ABSENT PROTECTOR RIDER COST THIS CLAIM")
    lines.append("")

    for item in simulation["rider_dependent_items"]:
        lines.append(f"    • {item['item']:<35} ₹{item['amount']:>8,.2f}")

    lines.append("")
    lines.append(f"    Total lost due to absent rider: "
                 f"₹{simulation['recoverable_amount']:,.2f}")
    lines.append("")
    lines.append("─" * W)
    lines.append("")
    lines.append("  THE CASE FOR ADDING THE PROTECTOR RIDER AT RENEWAL")
    lines.append("")
    lines.append("  The Protector Rider is available on Optima Restore.")
    lines.append("  It covers all Annexure I consumables — gloves, masks,")
    lines.append("  syringes, CSSD, PPE and 60+ other items deducted in")
    lines.append("  every hospitalisation without it.")
    lines.append("")
    lines.append(f"  This single claim lost ₹{simulation['recoverable_amount']:,.2f}.")
    lines.append("  Ask your agent for the Protector Rider annual premium.")
    lines.append("  If the premium is less than ₹"
                 f"{simulation['recoverable_amount']:,.2f}/year,")
    lines.append("  the rider pays for itself in one hospitalisation.")
    lines.append("")
    lines.append("─" * W)
    lines.append("")
    lines.append("  RENEWAL CHECKLIST")
    lines.append("")
    lines.append("  [ ] Ask agent: What is the Protector Rider annual premium?")
    lines.append("  [ ] Compare premium vs ₹"
                 f"{simulation['recoverable_amount']:,.2f} lost this claim")
    lines.append("  [ ] Add Protector Rider at next renewal if premium is viable")
    lines.append("  [ ] Confirm rider covers Annexure I items in writing")
    lines.append("")
    lines.append("=" * W)

    return "\n".join(lines)


# ── Full Report Orchestrator ────────────────────────────────────────────────────

def generate_full_report(
    settlement_path: Path = SETTLEMENT_FILE,
    user_schedule_path: Path = USER_SCHEDULE_FILE
) -> dict:
    """
    Orchestrates the full Symmetry Report.
    1. Runs audit engine
    2. Loads user schedule
    3. Determines route
    4. Generates all three documents
    5. Saves to reports/GPS_{claim_id}/
    Returns dict with route taken and file paths.
    """

    # Step 1 — Run audit
    audit_data = run_audit(settlement_path)

    # Step 2 — Load user schedule
    raw_schedule = json.loads(user_schedule_path.read_text(encoding="utf-8"))

    # Step 3 — Load settlement for claim header (non-PII fields only)
    raw_settlement = json.loads(settlement_path.read_text(encoding="utf-8"))
    header = raw_settlement.get("claim_header", {})
    meta   = raw_settlement.get("_schema_meta", {})

    claim_header = {
        "claim_reference":  meta.get("claim_reference", "UNKNOWN"),
        "policy_number":    meta.get("policy_number", "UNKNOWN"),
        "settlement_date":  header.get("admission_date", "UNKNOWN"),
        "hospital":         header.get("hospital", "UNKNOWN"),
        "procedure":        header.get("procedure", "UNKNOWN"),
        "admission_date":   header.get("admission_date", "UNKNOWN"),
        "discharge_date":   header.get("discharge_date", "UNKNOWN"),
    }

    # Step 4 — Determine route
    route, route_reason = determine_rider_route(raw_schedule)

    # Step 5 — Generate documents
    doc1 = generate_hospital_memo(audit_data["memo"], claim_header)
    doc2 = generate_settlement_comparison(audit_data)
    doc3 = generate_rider_output(route, audit_data, claim_header)

    # Step 6 — Save to reports folder organised by claim ID
    claim_id     = meta.get("claim_reference", "UNKNOWN").replace("-", "_")
    report_dir   = REPORTS_DIR / f"GPS_{claim_id}"
    report_dir.mkdir(parents=True, exist_ok=True)

    path1 = report_dir / "hospital_memo.txt"
    path2 = report_dir / "settlement_comparison.txt"
    path3 = report_dir / "rider_output.txt"

    path1.write_text(doc1, encoding="utf-8")
    path2.write_text(doc2, encoding="utf-8")
    path3.write_text(doc3, encoding="utf-8")

    return {
        "route":        route,
        "route_reason": route_reason,
        "report_dir":   str(report_dir),
        "files": {
            "hospital_memo":         str(path1),
            "settlement_comparison": str(path2),
            "rider_output":          str(path3)
        },
        "audit_summary": {
            "total_asymmetry":  audit_data["asymmetry"]["total_asymmetry_payload"],
            "invisible_loss":   audit_data["asymmetry"]["layer_1_invisible_loss"]["total"],
            "visible_loss":     audit_data["asymmetry"]["layer_2_visible_loss"]["total"],
            "recoverable":      audit_data["simulation"]["recoverable_amount"]
        }
    }


# ── Main ────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    W = 72
    print("\n" + "═" * W)
    print("  EZER SYMMETRY REPORT — V3.2")
    print("═" * W)

    try:
        result = generate_full_report()

        print(f"\n  Route Taken     : {result['route']} — ", end="")
        if result["route"] == "A":
            print("Grievance Mode")
        elif result["route"] == "B":
            print("Gap Awareness Mode")
        else:
            print("Renewal Action Mode")

        print(f"\n  Route Reason    : {result['route_reason'][:65]}...")
        print(f"\n  Report saved to : {result['report_dir']}")
        print(f"\n  Documents generated:")
        print(f"    ✅ Document 1 — Hospital Irregularity Memo")
        print(f"    ✅ Document 2 — Settlement Comparison")
        print(f"    ✅ Document 3 — Rider Output (Route {result['route']})")

        s = result["audit_summary"]
        print(f"\n  {'── ASYMMETRY SUMMARY ':─<{W-2}}")
        print(f"\n  Invisible Loss (Hospital Flags)  : ₹{s['invisible_loss']:>12,.2f}")
        print(f"  Visible Loss (Insurer Deductions): ₹{s['visible_loss']:>12,.2f}")
        print(f"  Total Asymmetry Payload          : ₹{s['total_asymmetry']:>12,.2f}")
        print(f"  Recoverable (Rider Simulation)   : ₹{s['recoverable']:>12,.2f}")

    except Exception as e:
        print(f"\n  ❌ Error: {e}")
        raise

    print("\n" + "═" * W + "\n")
